---
permalink: administration/reference_parameters_to_set_up_ossv.html 
sidebar: sidebar 
keywords: parameter, open, system, snapvault, ossv, enable, homedir, snapshot 
summary: 'Vários parâmetros são necessários para configurar o Open Systems SnapVault (OSSV).' 
---
= Parâmetros para configurar OSSV
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vários parâmetros são necessários para configurar o Open Systems SnapVault (OSSV).

|===
| Parâmetro | Definição | Descrição 


 a| 
NTAP_OSSV_ENABLE
 a| 
(Y
| N) 


 a| 
Permite a integração do OSSV. Este parâmetro deve ser usado em combinação com o parâmetro NTAP_OSSV_HOMEDIR. O OSSV também é necessário no host que executa o Snap Creator. No OSSV, a lógica de retenção de política lida com as políticas baseadas apenas nas políticas predefinidas do Snap Creator. Ele não suporta nenhum objeto de política.


NOTE: Quando este parâmetro OSSV está ativado, o caminho é especificado como volumes. Ao especificar caminhos no Windows para OSSV, os dois pontos (:) não devem ser usados. Por exemplo, se o caminho for e:
 a| 
NTAP_OSSV_HOMEDIR
 a| 
/usr/SnapVault



 a| 
Define o caminho para o diretório home do OSSV (/usr/SnapVault).
 a| 
NTAP_OSSV_FS_SNAPSHOT
 a| 
(Y



| N)  a| 
Necessário para definir o parâmetro NTAP_OSSV_FS_SNAPSHOT_CREATE_CMD.permite criar uma cópia Snapshot do sistema de arquivos usando o comando Open System ou sistema de arquivos. A cópia Snapshot do sistema de arquivos é então transferida para o sistema de storage usando o SnapVault.
 a| 
NTAP_OSSV_FS_SNAPSHOT_CREATE_CMD

|===