---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: Você pode personalizar o keystore ou certificado padrão usando o comando keytool que está disponível no Windows e UNIX. 
---
= Personalizar o keystore padrão
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode personalizar o keystore ou certificado padrão usando o comando keytool que está disponível no Windows e UNIX.

O comando keytool é fornecido pelo Java. Em alguns ambientes, você pode ter que mudar para o diretório de instalação Java para executar o comando keytool.

Snap Creator não suporta lojas de confiança.

. Pare o Snap Creator Agent.
. Gere um novo keystore com um único certificado:
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`

+
Keytool -genkeypair -alias servicekey -keystore serviceKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. Copie o arquivo keystore para o diretório scAgent4,3.0/etc/.
. Atualize os parâmetros de senha KEYSTORE_file e KEYSTORE_PASS no arquivo de configuração do Snap Creator Agent (scAgent4,3.0/etc/allowed_Commands.config).
. Inicie o Snap Creator Agent.


*Informações relacionadas*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Iniciando, verificando e parando o Snap Creator Agent no Windows]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[Iniciando, verificando e parando o Snap Creator Agent no UNIX]
