---
permalink: administration/task_setting_snap_creator_server_credentials.html 
sidebar: sidebar 
keywords: snap, creator, server, credentials, scadmin, port 
summary: 'Você pode armazenar as credenciais do Snap Creator Server (como nome de host do servidor ou endereço IP, configurações de porta, usuário e senha) para evitar inserir as credenciais na interface de linha de comando (CLI) várias vezes. Quando necessário, você pode remover as credenciais armazenadas.' 
---
= Configurando credenciais do Snap Creator Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode armazenar as credenciais do Snap Creator Server (como nome de host do servidor ou endereço IP, configurações de porta, usuário e senha) para evitar inserir as credenciais na interface de linha de comando (CLI) várias vezes. Quando necessário, você pode remover as credenciais armazenadas.

O procedimento para definir as credenciais do Snap Creator Server é o mesmo para Windows e UNIX. O procedimento a seguir usa exemplos do ambiente UNIX.

. No host onde o Snap Creator Server está instalado, digite o seguinte comando no diretório de instalação do Snap Creator Server:
+
`/install_path/scServer4.3/snapcreator --credentials`

+
A saída a seguir é exibida, permitindo que você defina as credenciais padrão para o Snap Creator Server:

+
[listing]
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----
. Insira as informações apropriadas para cada entrada.
+
Depois de inserir sua entrada para a entrada Config name, as credenciais são salvas e a seguinte mensagem é exibida: INFO: Credenciais CLI armazenadas com êxito. As credenciais são armazenadas no arquivo snapcreatoror.credentials no diretório .snapcreatoror ou na pasta no diretório inicial.

. Se você quiser remover as credenciais armazenadas, exclua o arquivo snapcreator.credentials.

