---
permalink: installation/reference_cli_commands_for_creating_svm_roles.html 
sidebar: sidebar 
keywords: cli, commands, creating, svm, roles, role create 
summary: A tabela a seguir lista os comandos necessários para criar uma função para um novo usuário SVM. 
---
= Comandos CLI para criar funções SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A tabela a seguir lista os comandos necessários para criar uma função para um novo usuário SVM.

|===
| Nome do diretório de comando | Comando a ser executado 


 a| 
adduser
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "adduser" -vserver SnapCreator



 a| 
event generate-AutoSupport-log
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "event Generate-AutoSupport-log" -vserver SnapCreator



 a| 
comentário lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun comment" -vserver SnapCreator



 a| 
lun criar
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun create" -vserver SnapCreator



 a| 
eliminação lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun delete" -vserver SnapCreator



 a| 
geometria lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun Geometry" -vserver SnapCreator



 a| 
lun igrop add
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun igroup add" -vserver SnapCreator



 a| 
lun igrop criar
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun igroup create" -vserver SnapCreator



 a| 
conjunto de grupos lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun igroup set" -vserver SnapCreator



 a| 
show de grupos de lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun igroup show" -vserver SnapCreator



 a| 
mapa lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun map" -vserver SnapCreator



 a| 
mostra de mapeamento lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun mapping show" -vserver SnapCreator



 a| 
modificação de lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun Modify" -vserver SnapCreator



 a| 
movimento lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun move" -vserver SnapCreator



 a| 
lun offline
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun off-line" -vserver SnapCreator



 a| 
lun online
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun online" -vserver SnapCreator



 a| 
redimensionar lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun resize"-vserver SnapCreator



 a| 
mostra lun
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun show" -vserver SnapCreator



 a| 
lun desmapear
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "lun unmap" -vserver SnapCreator



 a| 
rede
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "network" -vserver SnapCreator



 a| 
conexões de rede
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "network connections" -vserver SnapCreator



 a| 
ligações de rede ativas
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "Network Connections ative" -vserver SnapCreator



 a| 
show de escuta de conexões de rede
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "Network Connections listening show" -vserver SnapCreator



 a| 
interface de rede
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "network interface" -vserver SnapCreator



 a| 
grupos de roteamento de rede
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "network routing-groups" -vserver SnapCreator



 a| 
restauração de arquivo
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "restore-file" -vserver SnapCreator



 a| 
SnapMirror
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "SnapMirror" -vserver SnapCreator



 a| 
versão
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "version" -vserver SnapCreator



 a| 
volume
 a| 
Criar função -função VSERVERRBACROLE_New -cmddirname "volume"



 a| 
dimensionamento automático de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume automático" -vserver SnapCreator



 a| 
clone de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume clone" -vserver SnapCreator



 a| 
clone de volume criar
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume clone create" -vserver SnapCreator



 a| 
criar volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume create" -vserver SnapCreator



 a| 
destruição de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume Destroy" -vserver SnapCreator



 a| 
eficiência de volume desligada
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume Efficiency Off" -vserver SnapCreator



 a| 
eficiência de volume ativada
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume Efficiency on" -vserver SnapCreator



 a| 
início da eficiência de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume Efficiency start" -vserver SnapCreator



 a| 
show de eficiência de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume Efficiency show" -vserver SnapCreator



 a| 
ficheiro de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume file" -vserver SnapCreator



 a| 
clone de arquivo de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume file clone" -vserver SnapCreator



 a| 
clone de arquivo de volume criar
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume file clone create" -vserver SnapCreator



 a| 
modificação do volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume Modify" -vserver SnapCreator



 a| 
montagem de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume mount" -vserver SnapCreator



 a| 
volume off-line
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume off-line" -vserver SnapCreator



 a| 
apresentação do volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume show" -vserver SnapCreator



 a| 
tamanho do volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume size" -vserver SnapCreator



 a| 
criar instantâneo de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume snapshot create" -vserver SnapCreator



 a| 
eliminar instantâneo do volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume snapshot delete" -vserver SnapCreator



 a| 
restauração de snapshot de volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume snapshot restore" -vserver SnapCreator



 a| 
desmontar o volume
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "volume desmontar" -vserver SnapCreator



 a| 
a regra de política de exportação do svm é exibida
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver export-policy rule show" -vserver SnapCreator



 a| 
exibição da política de exportação do svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver export-policy show" -vserver SnapCreator



 a| 
svm fcp
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp" -vserver SnapCreator



 a| 
mostra do iniciador fcp da svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp iniciador show" -vserver SnapCreator



 a| 
apresentação do fcp do svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp show" -vserver SnapCreator



 a| 
status do svm fcp
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver fcp status" -vserver SnapCreator



 a| 
svm iscsi
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi" -vserver SnapCreator



 a| 
apresentação da ligação iscsi de svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi Connection show" -vserver SnapCreator



 a| 
lista de acessórios da interface iscsi de svm adicionar
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi interface accesslist add" -vserver SnapCreator



 a| 
mostra a lista de acessórios da interface iscsi de svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi interface accesslist show" -vserver SnapCreator



 a| 
consulta do svm iscsi isns
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi isns query" -vserver SnapCreator



 a| 
nome de identificação iscsi da svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi nodename" -vserver SnapCreator



 a| 
apresentação de sessão iscsi de svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi session show" -vserver SnapCreator



 a| 
apresentação iscsi de svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver iscsi show" -vserver SnapCreator



 a| 
estado iscsi do svm
 a| 
Função criar -função VSERVERRBACROLE_New -cmddirname "vserver iscsi status" -vserver SnapCreator



 a| 
svm nfs
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver nfs" -vserver SnapCreator



 a| 
status nfs do svm
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver nfs status" -vserver SnapCreator



 a| 
os hosts dns dos serviços de svm são exibidos
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service dns hosts show" -vserver SnapCreator



 a| 
serviços de svm unix-group create
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-group create" -vserver SnapCreator



 a| 
os serviços de svm show unix-group
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-group show" -vserver SnapCreator



 a| 
serviços de svm unix-user create
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-user create" -vserver SnapCreator



 a| 
serviços de svm unix-user show
 a| 
Role create -role VSERVERRBACROLE_New -cmddirname "vserver services name-service unix-user show" -vserver SnapCreator

|===