---
permalink: installation/task_upgrading_the_snap_creator_server_3_6_x_on_windows.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 3.6.x, windows 
summary: Você pode atualizar diretamente do Snap Creator Server 3,6.x no Windows. 
---
= Atualizando o Snap Creator Server 3,6.x no Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar diretamente do Snap Creator Server 3,6.x no Windows.

* Se você tiver quaisquer nomes de usuário Snap Create que contenham carateres especiais, você deve ter renomeado esses usuários usando apenas carateres alfabéticos (a-z, A-Z) antes de executar a atualização.
* Você interrompeu os serviços do Snap Creator (`snapcreatorserverservice`e `snapcreatoragentservice`o ) antes de fazer backup dos diretórios do Snap Creator para garantir que os dados de backup sejam concluídos.
+
Por exemplo, você pode usar o snap-in Serviços para interromper os serviços:

+
.. Selecione *Iniciar* > *Executar* e digite `services.msc`.
.. Localize e selecione o serviço Snap Creator; em seguida, pare o serviço. Alternativamente, você pode abrir um prompt de comando e inserir os seguintes comandos:


+
[listing]
----
sc stop snapcreatorserverservice
sc stop snapcreatoragentservice
----
* Você fez o backup dos seguintes diretórios e de todos os subdiretórios e arquivos associados, dentro do diretório servidor 3,6.x (C: Arquivos de programas/NetApp/NetApp_Snap_Creator_Framework/scServer3,6.x):
+
** Base de dados Snap Creator (..
** Perfis e arquivos de configuração (.. Configurações)
** Logs (.. Logs) *Observação:* não exclua as cópias de backup do Snap Creator 3,6.x que você criou.


* (Opcional) se o Agente Criador de Snap estiver instalado no mesmo host que o servidor Criador de Snap, você deve fazer o backup do arquivo Agent.conf (arquivos de programas/NetApp/NetApp_Snap_Creator_Framework/scServer3,6.x config/Agent.conf)


Os caminhos fornecidos nas etapas a seguir referem-se ao caminho de instalação padrão do Windows. Suas informações de caminho podem diferir se os padrões não forem usados.

Depois que o processo de atualização estiver concluído, considere os seguintes problemas:

* Se o banco de dados do Snap Creator que é atualizado contiver algumas tarefas marcadas como "'em andamento'", o estado permanecerá o mesmo mesmo depois que o processo de atualização estiver concluído.
* O administrador padrão no Snap Creator mais recente deve ser um administrador no Snap Creator 3,6.x. Se o usuário 3,6.x não for um administrador, a atualização atribuirá uma função de operador ao usuário 3,6.x.
+
.. Pare os serviços Snap Creator se você ainda não o fez.
+
Para obter informações sobre como parar os serviços, consulte os detalhes fornecidos anteriormente neste tópico.

.. Desinstale o Snap Creator (para Windows) selecionando *Iniciar* > *programas* > *Snap Creator* > *Desinstalar o NetApp Snap Creator*.
+
Para obter detalhes, consulte informações sobre como desinstalar o Snap Creator no Windows.

.. Instale o servidor Snap Creator mais recente.
+
Para obter detalhes, consulte as informações sobre como instalar o Snap Creator Server no Windows.

.. Se você selecionou para iniciar o Snap Creator Server como um serviço quando instalou o Snap Creator Server mais recente, pare o serviço.
+
Para obter informações sobre como parar o serviço, consulte os detalhes fornecidos anteriormente neste tópico.

.. Exclua a mais recente pasta de banco de dados do servidor Snap Creator (C: Arquivos de programas/NetApp/Snap_Creator_Framework/scServer4,1.x).
.. Copie o diretório de banco de dados do Snap Creator 3,6.x com backup para o local mais recente (C: Arquivos de programas/NetApp/Snap_Creator_Framework/scServer4,1.x).
.. Copie os perfis e o diretório de configuração do Snap Creator 3,6.x com backup para o local mais recente (C: Arquivos de programas/NetApp/scServer4,1.x configurações do mecanismo).
.. Copie o diretório de logs do Snap Creator 3,6.x com backup para o local mais recente (C: Arquivos de programas/NetApp/Snap_Creator_Framework/scServer4,1.x).
.. Abra um prompt de comando e altere o diretório para o subdiretório do motor no caminho de instalação do Snap Creator (C: Arquivos de programas/NetApp/Snap_Creator_Framework/scServer4,1.x).
.. Atualize o Snap Creator inserindo o seguinte comando: java -jar snapcreator.jar -upgrade




Depois que o processo de atualização estiver concluído, inicie o serviço Snap Creator Server fazendo um dos seguintes procedimentos:

* Use o snap-in Serviços e inicie o serviço.
* Digite o seguinte comando a partir de um prompt de comando: `sc start snapcreatorserverservice`


Além disso, você deve validar a inicialização da GUI do Snap Creator Framework navegando até o host local na porta especificada (https://IP_address:gui_port[]).

Você deve se conetar usando HTTPS; caso contrário, a conexão não será automaticamente redirecionada para uma conexão HTTPS e a GUI não funcionará.

*Informações relacionadas*

xref:concept_installing_the_snap_creator_server.adoc[Instalar o Snap Creator Server]

xref:task_uninstalling_snap_creator_on_windows.adoc[Desinstalar o Snap Creator no Windows]
