---
permalink: installation/task_creating_a_snap_creator_user_for_clustered_ontap.html 
sidebar: sidebar 
keywords: creating, create, snap, center, user, ontap 
summary: 'Para o Clustered Data ONTAP, você deve criar usuários para o Snap Creator. No entanto, o tipo de usuário que você cria depende da versão do Clustered Data ONTAP. Os dois tipos de usuários são um usuário de cluster e um usuário de máquina virtual de storage (SVM).' 
---
= Criando um usuário Snap Creator para Clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para o Clustered Data ONTAP, você deve criar usuários para o Snap Creator. No entanto, o tipo de usuário que você cria depende da versão do Clustered Data ONTAP. Os dois tipos de usuários são um usuário de cluster e um usuário de máquina virtual de storage (SVM).

Crie os seguintes usuários, com as funções apropriadas, conforme definido no _Guia de administração da estrutura do Snap Creator_, para sua versão do Data ONTAP:

* Versões do Data ONTAP anteriores ao Clustered Data ONTAP 8.2: Crie um cluster e um usuário SVM.
* Clustered Data ONTAP 8.2 ou posterior: Crie um usuário SVM.


Para aumentar a segurança, você deve criar um usuário e uma função do Data ONTAP especificamente para o Snap Creator. Como alternativa, você pode usar outras contas de usuário, como admin ou vsadmin.

Para obter mais informações sobre como criar uma função Snap Creator usando a CLI, consulte referências relacionadas.

Ambos os tipos de usuário exigem acesso à biblioteca Data ONTAPI. Além disso, um LIF de gerenciamento também é necessário para o Clustered Data ONTAP, independentemente da versão.

Os dois utilizadores não são permutáveis. Por exemplo, o usuário do cluster não tem acesso às APIs necessárias para executar certas ações, como a criação de uma cópia Snapshot. Isso é verdade mesmo que você use a conta de administrador do cluster padrão. As contas SVM devem usar a função *vsadmin* ou uma função criada pelo cliente para que o Snap Creator funcione corretamente.

Você deve executar esse procedimento uma vez em cada SVM e cluster em que o Snap Creator seja usado.

Para facilitar o uso, as instruções a seguir referem-se às funções admin e vsadmin; no entanto, você pode substituir esses nomes de funções pelas funções criadas.


NOTE: Você não deve copiar e colar comandos diretamente deste documento; erros (como carateres transferidos incorretamente causados por quebras de linha e retornos difíceis) podem resultar. Copie e cole os comandos deste procedimento em um editor de texto, verifique os comandos e insira-os na CLI.

. Crie o usuário SVM_username01 com a função apropriada (vsadmin ou a função criada para o usuário) na SVM_nameSVM e habilite o acesso à biblioteca ONTAPI digitando o seguinte comando e uma senha de usuário:
+
[listing]
----
security login create -username svm_username01
-vserver svm_name -application ontapi
-authmethod password -role vsadmin

Please enter a password for user 'svm_username01':
Please enter it again:
----
. _(apenas para versões anteriores ao Clustered Data ONTAP 8.2)_ Crie um usuário de cluster digitando o seguinte comando e uma senha de usuário:
+
[listing]
----
security login create -username svm_username02
-vserver svm_clustername -application ontapi
-authmethod password -role admin

Please enter a password for user 'svm_username02':
Please enter it again:
----


*Informações relacionadas*

xref:reference_cli_commands_for_creating_a_role_for_a_snap_creator_user_in_clustered_data_ontap.adoc[Comandos CLI para criar uma função para um usuário do Snap Creator no Clustered Data ONTAP]
