---
permalink: domino-ops/delete_reference_trademark.html 
sidebar: sidebar 
keywords: trademarks 
summary: Informações sobre marcas comerciais 
---
= Informações sobre marcas comerciais
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


SANtricity SnapCenter SnapIntegrator SnapMirror SnapRestore SolidFire SyncMirror NetApp, SecureShare SnapCopy SnapLock SnapMover SnapValidator SolidFire Helix Tech OnTap, ONTAP SnapDrive SnapManager SnapProtect SnapVault StorageGRID WAFL, RAID-TEC, SANscreen, SANshare, OnCommand, ONTAP, FlexScale, FlexShare, RAID DP, FPolicy, alimentado por SolidFire, GetSuccessful, Helix Design, LockONTVault, Gerenciar NetApp, NetApp Insight, MultiStore, ONTAP, MetroCluster, FlexGroup, FlexPod, FlexVol, FlexArray, FlexCache, FlexClone, Data ONTAP, Data ONTAP, Flash Accel, Active IQ, AltaVault, AutoSupport, Todas as outras marcas ou produtos são marcas comerciais ou marcas registradas de seus respetivos proprietários e devem ser tratadas como tal. Uma lista atual de marcas comerciais da NetApp está disponível na Web.

http://www.netapp.com/us/legal/netapptmlist.aspx[]
